### ISSUE TITLE
Define standard data structures

### ISSUE THREAD

**Issue by isysd** [GitGuild/gitguild_whitepaper#5]
The data structures that are created in the guild data directory are what makes a git blockchain binding and meaningful rather than just a pretty math tree. Currently the file structures defined are:

| File             | Path       | Description           |
|----------------|------------|------------------------|
| charter.md  | .gg         | Bylaws of the guild |
| members.csv | .gg      | List of members   |
| ledger.dat   | .gg         | Ledger-cli data file for the guild finances |

Additionally, the following git branches are reserved.

| Branch             | Maintainer       | Description           |
|--------------------|--------------------|------------------------|
| master             | Last member to commit  | The master branch is a protected communal branch. It reflects the latest valid state of the sum of all member branches. |
| {member-name}             | {member-name}  | Each member must maintain their own branch, and use this branch for submitting votes (commits) or voting on the commits of others (merging). |

**Comment by isysd** [comment]
This is at least partially included in the whitepaper now. https://github.com/GitGuild/gitguild_whitepaper/blob/master/whitepaper.md#file-structure

**Comment by f3rnando** [comment]
Ok, I this pretty muchs clears the concept I believe. I was waiting to be really sure before pushing my branch to track, still confused with the master branch state "provableness". Members should unilaterally compare all {member-name} branches against master to be confident that it is valid? Is this the weaker point?

**Comment by isysd** [comment]
Yes, you've got the concept. There is some hand waving in data synchronization, but if you assume each member runs a node that always keeps an up to date copy of each member's branch, then the master branch can be safely reconstructed from any point in time.

I would say the data synchronization is a weak point, but is addressable in any number of ways. Using a trusted git server is a short-term hack, and marketing ploy to get github users.

The other weak point here is vote counting. Standardizing that would be quite helpful. I'm considering requiring people to write ledger-cli vote counting scripts that will be strict. Ledger seems capable of this, and an obvious choice for counting things...

**Comment by isysd** [comment]
I re-imagined these a bit, adding new directories and documentation of sidechains. Closing this now, since at least the first draft of this format is done.
